language: c++
  
before_install:
  - bash scripts/travis.linux.sh before_install

before_script:
  - bash scripts/travis.linux.sh before_script

script:
  - bash scripts/travis.linux.sh script

deploy:
  provider: script
  script: bash scripts/travis.linux.sh deploy
  on:
    branch: master
  
after_script:
  - bash scripts/travis.linux.sh after_script
  
