language: c++
  
before_install:
  - export DEBUG=-x
  - bash scripts/travis.linux.sh before_install 1 2 3

before_script:
  - export DEBUG=-x; bash scripts/travis.linux.sh before_script

script:
  - export DEBUG=-x
  - bash scripts/travis.linux.sh script 1 2 3
  
after_script:
  - export DEBUG=-x; bash scripts/travis.linux.sh after_script
  
