language: c++
  
_before_install:
  - pwd
  - env
  - export DEBUG=1
  - bash scripts/travis.linux.sh before_install 1 2 3

_before_script:
  - export DEBUG=1; bash scripts/travis.linux.sh before_script

script:
  - pwd
  - env
  - export DEBUG=1
  - bash scripts/travis.linux.sh script
  
_after_script:
  - export DEBUG=1; bash scripts/travis.linux.sh after_script
  
