language: c++
  
before_install:
  - export DEBUG=1; bash scripts/travis.linux.sh before_install

before_script:
  - export DEBUG=1; bash scripts/travis.linux.sh before_script

script:
  - export DEBUG=1; bash scripts/travis.linux.sh script
  
after_script:
  - export DEBUG=1; bash scripts/travis.linux.sh after_script
  
